// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Muuzika.Gateway.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Muuzika.Gateway.Migrations
{
    [DbContext(typeof(MuuzikaDbContext))]
    partial class MuuzikaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Muuzika.Gateway.Entities.AuthenticatableEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_authenticatables_created_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_authenticatables_updated_by_id");

                    b.ToTable("authenticatables");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Muuzika.Gateway.Entities.ServerEntity", b =>
                {
                    b.HasBaseType("Muuzika.Gateway.Entities.AuthenticatableEntity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_servers_name");

                    b.ToTable("servers");
                });

            modelBuilder.Entity("Muuzika.Gateway.Entities.UserEntity", b =>
                {
                    b.HasBaseType("Muuzika.Gateway.Entities.AuthenticatableEntity");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Muuzika.Gateway.Entities.AuthenticatableEntity", b =>
                {
                    b.HasOne("Muuzika.Gateway.Entities.AuthenticatableEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_authenticatables_authenticatables_created_by_id");

                    b.HasOne("Muuzika.Gateway.Entities.AuthenticatableEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_authenticatables_authenticatables_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Muuzika.Gateway.Entities.ServerEntity", b =>
                {
                    b.HasOne("Muuzika.Gateway.Entities.AuthenticatableEntity", null)
                        .WithOne()
                        .HasForeignKey("Muuzika.Gateway.Entities.ServerEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_servers_authenticatables_id");
                });

            modelBuilder.Entity("Muuzika.Gateway.Entities.UserEntity", b =>
                {
                    b.HasOne("Muuzika.Gateway.Entities.AuthenticatableEntity", null)
                        .WithOne()
                        .HasForeignKey("Muuzika.Gateway.Entities.UserEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_authenticatables_id");
                });
#pragma warning restore 612, 618
        }
    }
}
