INSERT INTO parameters (name, value) 
VALUES 
  ('SNOWFLAKE_EPOCH_OFFSET_MS', '1657560600000'),
  ('ROUND_DURATION_LEEWAY_MS', '1000'),
  ('ROUND_START_DELAY_MS', '5000'),
  ('MIN_USERNAME_LENGTH', '3'),
  ('MAX_USERNAME_LENGTH', '30'),
  ('MAX_PASSWORD_LENGTH', '50'),
  ('MAX_ROUNDS', '20'),
  ('MAX_PLAYERS', '64'),
  ('MAX_PLAYLIST_SIZE', '1000')
