upstream calculators {
    server host.docker.internal:50061;
    server host.docker.internal:50062;
}

upstream string_manipulators {
    server host.docker.internal:50061;
}

server {
    listen       50051;
    #listen  [::]:50051;
    server_name  grpc.muuzika.com;
    http2 on;

    #access_log  /var/log/nginx/host.access.log  main;

    location /muuzika.Calculator {
        grpc_pass grpc://calculators;
        error_page 502 = /error502grpc;
    }

    location /muuzika.StringManipulator {
        grpc_pass grpc://string_manipulators;
        error_page 502 = /error502grpc;
    }

    location / {
        grpc_pass grpc://host.docker.internal:50061;
    }
 
    location = /error502grpc {
        internal;
        default_type application/grpc;
        add_header grpc-status 14;
        add_header grpc-message "unavailable";
        return 204;
    }
}

