name: Registry Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: registry

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Run tests
        run: cargo test -- -Z unstable-options --format json --report-time > test-output.json
        env:
          RUSTC_BOOTSTRAP: 1

      - name: Convert test results to JUnit
        run: cargo2junit < test-output.json > test-results.xml

      - name: Show test results in GitHub UI
        uses: dorny/test-reporter@v1
        with:
          name: Registry Tests
          path: test-results.xml
          reporter: java-junit
