name: Registry Tests

on:
  push:
    paths:
      - 'registry/**'
      - 'proto/**'
  pull_request:
    paths:
      - 'registry/**'
      - 'proto/**'

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: registry

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Install cargo2junit
        run: cargo install cargo2junit

      - name: Run tests and generate JUnit report
        run: cargo test -- -Z unstable-options --format json --report-time | cargo2junit > test-results.xml
        continue-on-error: true
        env:
          RUSTC_BOOTSTRAP: 1

      - name: Show test results in GitHub UI
        uses: dorny/test-reporter@v1
        with:
          name: Registry Tests
          path: registry/test-results.xml
          reporter: java-junit
